export const questionsLvl1 = [
    {
        "id": 1,
        "BonneReponse": "A améliorer la position d'un site web sur les moteurs de recherche",
        "Categories": "SEO, c'est quoi ?",
        "Difficulte": "Facile",
        "MauvaiseReponses": ["A rien", "A améliorer la qualité d'un site web sur les moteurs de recherches","Toujours à rien"],
        "Question": "A quoi sert le SEO ? ",
    },
    {
        "id": 2,
        "BonneReponse": "2-3 mots-clés",
        "Categories": "Les mots-clés",
        "Difficulte": "Facile",
        "MauvaiseReponses": ["5-6 mots-clés","10-12 mots-clés","Aucun mot-clés"],
        "Question": "De combien de mots-clés est composé un nom de domaine ?",
    },
    {
        "id": 3,
        "BonneReponse": "Modifier la balise \"Robots\" de la page",
        "Categories": "Les outils",
        "Difficulte": "Difficile",
        "MauvaiseReponses": ["Bloquer la page","Archiver la page","Supprimer la page"],
        "Question": "Je souhaite bloquer l'indexation d'une page par Google, que dois-je faire?",
    },
    {
        "id": 4,
        "BonneReponse": "Les liens éditoriaux naturels",
        "Categories": "Architecture du site",
        "Difficulte": "Difficile",
        "MauvaiseReponses": ["Les liens éditoriaux non naturels"],
        "Question": "Quel type de lien est considéré comme apportant le plus de valeur ?",
    },
    {
        "id": 5,
        "BonneReponse": "La balise Meta Title",
        "Categories": "Les balises",
        "Difficulte": "Difficile",
        "MauvaiseReponses": ["La balise Meta Description","La balise Meta Keywords","La balise Image"],
        "Question": "Dans la page de résultats Google, à quelle balise correspond la ligne principale en bleu ?",
    },
    {
        "id": 9,
        "BonneReponse": "Pour un lien cliquable",
        "Categories": "Architecture du site",
        "Difficulte": "Facile",
        "MauvaiseReponses": ["Pour les titres d'oeuvre","Pour faire jolie","Pourquoi pas ?"],
        "Question": "Dans quel cas doit-on souligner un texte ?",
    },
    {
        "id": 11,
        "BonneReponse": "Non",
        "Categories": "SEO, c'est quoi ?",
        "Difficulte": "Facile",
        "MauvaiseReponses": ["Oui"],
        "Question": "Dois je savoir coder pour procéder moi-meme à l'optimisation SEO ?",
    },
    {
        "id": 16,
        "BonneReponse": "60",
        "Categories": "Les balises",
        "Difficulte": "Facile",
        "MauvaiseReponses": ["200", "100", "20"],
        "Question": "Combien de caractères max doit comporter la balise Title pour un bon affichage dans les résultats Google ?",
    },
    {
        "id": 17,
        "BonneReponse": "Ordinateur, tablette, téléphone",
        "Categories": "Les mots-clés",
        "Difficulte": "Facile",
        "MauvaiseReponses": ["je cherche à acheter un appareil électronique"],
        "Question": "Quel est le mot clé ?",
    },
    {
        "id": 18,
        "BonneReponse": "Une annonce Google Ads",
        "Categories": "Les outils",
        "Difficulte": "Facile",
        "MauvaiseReponses": ["Une annonce Google trends", "Une annonce Google Analystics","Une annonce LeBoncoin"],
        "Question": "Qu'est-ce qu'un lien sponsorisé ?",
    }
]